### ISSUE TITLE
last setNotification() not finish Error

### ISSUE THREAD

**Issue by maxakash** [sorz/gattkt#1]
I am sometimes getting the "last setNotification() not finish" error when I am using 
```
   gattIo.enableNotification(charControl)
   gattIo.clearGattCharacteristicChangeQueue(charControl)

```

Here is the screen shot of the error.
![image](https://user-images.githubusercontent.com/17406944/100518294-aeb77680-31b6-11eb-8dcd-d07ba5fb31ae.png)

**Comment by sorz** [comment]
Did you have two threads/coroutines that invoke enableNotification()/enableIndication() on one char at the same time?

**Comment by maxakash** [comment]
I have solved that.
But I wanted some help from you. I am connecting to my bluetooth device(mi band 5) every time user goes to a specific activity through your MiBand.kt(your mi band export project).
But I don't think this is the best approach. Also is there any callback to ```device.connectGattIo(context)``` like in case of ```device.connectGatt()```
