### ISSUE TITLE
V/FA: Inactivity, disconnecting from the service

### ISSUE THREAD

**Issue by maxakash** [sorz/gattkt#2]
I am using your library to change firmware on my device. Most of the times it works fine. But sometimes it throws error
The error is thrown when below line is logged
```
V/FA: Inactivity, disconnecting from the service

```
Please suggest any fix.

Thanks

**Comment by sorz** [comment]
https://stackoverflow.com/questions/46080700/v-fa-inactivity-disconnecting-from-the-service/47485195

It seems a Firebase related error, not a error from the gattkt library.
